run:
  timeout: 5m
  concurrency: 4

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - gosimple

issues:
  exclude-dirs:
    - src
    - tests/testdata
